---
title: "codebook"
author: "YC"
date: "2024-05-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This is the codebook for my submission of the "averagedata.txt" data set (which is the answer to step 5 of the instructions.)  

There are a total of 180 observations and 69 variables. In this code book I will walk you through the 69 variables first and then the 180 observations.

The 69 variables are described as the following:

### Variable 1: subject
This refer to an identifier of the subject (i.e. volunteer) who carried out the experiment. The values of this variable range from 1 to 30, as there are 30 subjects in the experiment.

### Variable 2: activity.names
This refer to the activity each subject performed during the experiment. There are six kind of values for this variable: WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING

### Variable 3: activity.labels
This is a class label which directly links to its respective activity name:  
1 -> WALKING  
2 -> WALKING_UPSTAIRS  
3 -> WALKING_DOWNSTAIRS  
4 -> SITTING  
5 -> STANDING  
6 -> LAYING

### Variable 4 to Variable 69
These variables are means of measurements from a wide variety of signals. Since they are means, every variable name contain a sufix '_mean'. The rest of a variable name is a combination of various aspects of signals, which are explained as the following:    

**time / frequency:** 'time' denotes time domain signals; 'frequency' denotes frequency domain signals  

**Body / Gravity:** 'Body' denotes body acceleration signals; 'Gravity' denotes gravity acceleration signals  

**Accelerometer / Gyroscope:** 'Accelerometer' denotes accelerometer signals; 'Gyroscope' denotes gyroscope signals

**Jerk:** 'Jerk' denotes Jerk signals

**Magnitude:** 'Magnitude' denotes the magnitude of the three-dimensional signals, calculated using the Euclidean norm

**-mean / -std: ** '-mean' denotes the mean value estimated from the signals; '-std' denotes the standard deviation estimated from the signals

**-X / -Y / -Z: ** '-XYZ' denotes 3-axial signals in the X, Y and Z directions.


### Observations (i.e. rows)
The 180 observations are all unique with respect to 'subject' and 'activity.names' (and thus 'activity.labels').  
Each observation for each variable represents the mean value of the variable for each activity and each subject (as per the instruction of step 5 in the course project page).  

**  **




